### ISSUE TITLE
crowbar_batch: Exported Neutron barclamp is not correct

### ISSUE THREAD

**Issue by toabctl** [crowbar/barclamp-crowbar#1241]
When exporting the Neutron barclamp, I get:

```
root@crowbar:~ # crowbar_batch --username crowbar --password crowbar export neutron
---
proposals:
- barclamp: neutron
  attributes:
    service_password: secret
    rabbitmq_instance: default
    keystone_instance: default
    ml2_type_drivers:
    - vlan
    database_instance: default
    db:
      password: secret
  deployment:
    elements:
      neutron-server:
      - cluster:services
      neutron-l3:
      - cluster:services
```

But I have multiple ```ml2_type_drivers``` selected. In the raw view of the Neutron barclamp, I see:

```
"ml2_type_drivers": [
    "gre",
    "vlan"
  ],
```
